#!/bin/bash

DNS_URL_HOOK_WITH_DOMAIN=${DNS_URL_HOOK/~domain/$CERTBOT_DOMAIN}
DNS_URL_HOOK_WITH_VALIDATION=${DNS_URL_HOOK_WITH_DOMAIN/~validation/$CERTBOT_VALIDATION}

wget "$DNS_URL_HOOK_WITH_VALIDATION"

sleep $PROPAGATION_SECONDS
